services:
  # Laravel Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: "${APP_KEY}"
      APP_URL: http://localhost
      FRONTEND_URL: http://localhost:5173
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"

  # MySQL Database
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "8081:80"

  # React Frontend
  frontend:
    image: node:latest
    container_name: react_app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8000
    command: >
      sh -c "npm install && npm run dev"

volumes:
  mysql_data:
