name: CI Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer

      - name: Install Backend Dependencies
        run: |
          cd backend
          composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Set up Laravel Environment
        run: |
          cd backend
          cp .env.example .env
          php artisan key:generate

      - name: Set Laravel Permissions
        run: |
          cd backend
          chmod -R 777 storage bootstrap/cache

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install
          npm run build

      - name: Run Laravel Migrations
        run: |
          cd backend
          php artisan migrate --force
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_DATABASE: skillbridge
          DB_USERNAME: root
          DB_PASSWORD: ""

      - name: Run Tests
        run: |
          cd backend
          php artisan test
